// ─────────────────────────────────────────────────────────────
//  BluePrint Studio — Default Configuration
//
//  DO NOT edit this file per client.
//  This is the safety net. Every field has a value.
//  Client-specific values live in client.config.ts only.
// ─────────────────────────────────────────────────────────────

import type { ClientConfig } from './types';

export const defaultConfig: ClientConfig = {

  business: {
    name:        'Your Business Name',
    tagline:     'Professional services you can trust.',
    phone:       '+27 00 000 0000',
    email:       'info@yourbusiness.co.za',
    address:     '1 Main Street',
    city:        'Cape Town',
    province:    'Western Cape',
    postalCode:  '8001',
    country:     'South Africa',
    industry:    'general',
    logo:        '/images/logo.svg',
    logoAlt:     'Business logo',
    foundedYear: 2020,
  },

  theme: {
    primaryColor: '#1a1a2e',
    accentColor:  '#e94560',
    fontHeading:  'Montserrat',
    fontBody:     'Inter',
  },

  seo: {
    title:         'Your Business Name | Professional Services in Cape Town',
    description:   'Professional services in Cape Town. Contact us today for a free quote.',
    ogImage:       '/images/og-image.jpg',
    googleReviews: '',
  },

  hero: {
    style:       'image',
    headline:    'Professional Services You Can Trust',
    subheadline: 'Serving Cape Town and surrounds with quality workmanship and honest pricing.',
    ctaText:     'Get a Free Quote',
    ctaHref:     '#contact',
    image:       '/images/hero.webp',
    imageAlt:    'Professional services team at work',
    subtext:     'Free quotes · No obligation',
  },

  about: {
    heading:  'About Us',
    body:     'We are a professional services company based in Cape Town. With years of experience, we deliver quality results on time and on budget.',
    image:    '/images/about.webp',
    imageAlt: 'Our team',
    ctaText:  'Contact Us Today',
    ctaHref:  '#contact',
  },

  whyChooseUs: {
    heading: 'Why Choose Us',
    points: [
      { icon: 'shield-check', text: 'Fully licensed and insured for your peace of mind.' },
      { icon: 'clock',        text: 'Fast turnaround — most jobs completed within 48 hours.' },
      { icon: 'star',         text: 'Rated 5 stars by over 100 satisfied customers.' },
      { icon: 'phone',        text: 'Available 7 days a week — call us anytime.' },
    ],
  },

  services: {
    heading: 'Our Services',
    layout:  'grid',
    items: [
      {
        icon:        'wrench',
        name:        'Service One',
        description: 'A professional service delivered with care and precision.',
      },
      {
        icon:        'settings',
        name:        'Service Two',
        description: 'Another core service your business offers to clients.',
      },
      {
        icon:        'check-circle',
        name:        'Service Three',
        description: 'A third service that rounds out your core offering.',
      },
    ],
  },

  testimonials: {
    heading:    'What Our Clients Say',
    reviewsUrl: '',
    items: [
      {
        name:     'Sarah M.',
        location: 'Cape Town',
        text:     'Outstanding service from start to finish. I would highly recommend them to anyone.',
        rating:   5,
      },
      {
        name:     'James K.',
        location: 'Stellenbosch',
        text:     'Prompt, professional, and great value. Will definitely use again.',
        rating:   5,
      },
      {
        name:     'Linda T.',
        location: 'Bellville',
        text:     'They exceeded my expectations. The team was friendly and the work was perfect.',
        rating:   5,
      },
    ],
  },

  contact: {
    heading:          'Get a Free Quote',
    subheading:       'Fill in the form below and we will get back to you within 24 hours.',
    formFields:       ['name', 'phone', 'email', 'message'],
    serviceOptions:   [],
    showMap:          false,
    mapEmbedUrl:      '',
    recaptchaSiteKey: '',
  },

  footer: {
    tagline:     'Quality service you can rely on.',
    showSocials: false,
    facebook:    '',
    instagram:   '',
    linkedin:    '',
  },

  legal: {
    usesAnalytics:     false,
    analyticsProvider: '',
    lastUpdated:       '2026-05-04',
  },

  sections: {
    about:        true,
    whyChooseUs:  true,
    services:     true,
    testimonials: true,
  },
};
